backend:
  name: github
  repo: ariona/ariona.net
  branch: master # Branch to update (optional; defaults to master)
media_folder: "site/.vuepress/public/assets/img"
public_folder: "site/.vuepress/dist/"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "site/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        config:
          multiple: false